version: '3.9'

services:
    mssql:
        container_name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=${SA_PASSWORD}
        ports:
            - 1433:1433
        volumes:
            - mssql:/var/opt/mssql

volumes:
    mssql:
        name: mssql
        external: true
